"use client"

import { Inter } from "next/font/google";
import "../../styles/globals.css"
import Navbar from "@/appcomponents/Navbar"
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { Provider } from "react-redux";
import store from "@/redux-saga/store";
import { useRouter } from "next/navigation";
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
  //   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  const router = useRouter()
  const user = JSON.parse(localStorage.getItem("user"))
  if(!user){
    router.push("/user/login")
  }
  return (
    <html lang="en" className={"dark"}>
      <body className={inter.className}>
        <Provider store={store}>
        <Navbar />
        {children}
        </Provider>
      </body>
    </html>
  );
}
